### PR TITLE
Add support for more image formats

### PR DESCRIPTION
**Pull request by jwortmann**
This assigns the image icon to more image formats which are not recognized by default in ST.

This also means that the syntax for those files will be shown as "Image" instead of "Plain Text" now (I followed the practice for e.g. "Archives" here).

Ref.: https://github.com/SublimeText/AFileIcon/issues/22 and https://github.com/SublimeText/AFileIcon/commit/1ec5a6436a9e0d34a226561cad95a4c9d49bbf68

The file extensions are those which were added by the referenced commit in A File Icon.

### CODE REVIEW

**Comment by braver** [comment]
I think we'd want to have a different color for these file, so that you can recognise that thay are images that ST can't render.

**Comment by jwortmann** [comment]
Sounds like a good idea to me. Perhaps use the image icon tinted in grey for these file formats?

**Comment by braver** [comment]
Sounds good 👌🏻

**Comment by jwortmann** [comment]
I've named the new icons `file_type_image2`, please tell me in case you prefer a different name.

**Comment by braver** [comment]
Maybe file_type_imageunsupported and a note in the syntax file that it’s for images that ST doesn’t support natively. Otherwise 3 years from now I won’t have a clue what this is about 😄

**Comment by braver** [comment]
Great work, thanks! 🏆

**Pull request merged**
