### PR TITLE
Toit color icon

### PR DESCRIPTION
**Pull request by serjan-nasredin**
Hello! I want to add a color version of the [Toit programming language](https://www.toit.io/) icon.

### CODE REVIEW

**Comment by braver** [comment]
Thanks! Looks good basically except you seem to be deleting two other icons?

**Comment by serjan-nasredin** [comment]
Yeah @braver, I deleted the changes. I should have done a revert instead of making changes to the commit. But I didn't change anything in principle.

**Comment by braver** [comment]
Still those two deletions show in your diff. Maybe squash commits and clean up?

**Comment by serjan-nasredin** [comment]
Okay, wait.

**Comment by serjan-nasredin** [comment]
brah

**Comment by serjan-nasredin** [comment]
@braver, I broke a branch. :(

**Comment by braver** [comment]
LOL, just leave it as is, I'll fix it :)

**Comment by serjan-nasredin** [comment]
Thanks @braver! ❤️

**Pull request closed without merging**
