### PR TITLE
Replace Gulp build with Rust app

### PR DESCRIPTION
**Pull request by kellygravelyn**
Hey so up front: I totally don't expect you to merge this PR. Gulp works and I'm guessing more folks are setup with NPM than Rust. No need to change something that's already working for you. That said I wanted to open this up because I really love the work you've done to collect these icons and I wanted to share this with you or others using this repo in case it was useful in any way.

I was trying to make a set of the icons all purple for my personal Sublime theme. Problem for me is that the Gulp build on my M1 MacBook Air was taking nearly 3.5 minutes which is a long time to wait when I was trying to find just the right shade of purple.

To try and speed things up for me I tried converting it over to Rust. With this Rust version the output seems nearly identical (not exactly from what I can tell but close enough for my use), however the Rust version builds all the icons in under 2 seconds on my machine which is massively faster than the Gulp version.

So yeah here's a rewrite of your build in Rust that's about 100x faster than Gulp. Feel free to use it or ignore it but I wanted to share this back since I thought others might want to give it a try, particularly if playing around with different colors or new icons or whatever.

### CODE REVIEW

**Comment by braver** [comment]
Wow, thanks! I would really like to get rid of Gulp because it is extremely slow (as you noticed) and I’m constantly getting vulnerability warnings from GitHub about it. If the resulting PNGs are basically visually the same, let’s try and merge this!

**Comment by kellygravelyn** [comment]
Here's a side-by side of all the icons (the 48px versions) with Gulp vs Rust:

gulp-vs-rust

To be completely transparent I honestly have no idea which side is which. 😂 They all look pretty much the same except for GraphViz. Here's the Gulp output:

file_type_graphviz@3x_gulp

And Rust:

file_type_graphviz@3x

Obviously not good. I'll look into it and see if there's a reason why that one in particular doesn't render out the same.

**Comment by kellygravelyn** [comment]
Ok turns out [usvg](https://github.com/RazrFalcon/resvg/tree/master/usvg) which is used by the Rust app doesn't support the `<circle>` element which is why the GraphViz icon only had the rects. Also the way that SVG specified color didn't work with my admittedly hacky "search and replace in a string" color substitution. I've fixed that up and now can generate a good GraphViz icon. Here's what it looks like from Rust now:

file_type_graphviz@3x

Interestingly usvg says it doesn't support `<rect>` but the rects in the GraphViz logo render fine for me. Might be worth converting them to paths as well in the future for consistency, but it works for now. 🤷🏻‍♀️ 😆

**Comment by braver** [comment]
Awesome. SVG is surprisingly finicky, basically the only thing that works reliably is paths. But this looks pretty good 👍🏻 I need to try and see if I can get the build to run on my machine, but so far so good. Thanks so much for this!

**Comment by braver** [comment]
Fantastic. I'm instantly converted into a Rust fan! 👍🏻

**Comment by kellygravelyn** [comment]
🥳

I won’t claim it’s super great Rust code; I’m still learning the language and wasn’t too worried about error handling. But glad to see it working for you!

**Pull request merged**
